#!/bin/bash
[[ -n `git config --global repo.dir` ]] \
  && dir=`git config --global repo.dir` || dir=~/

IFS=$'\n'
for name in $(find $dir -type d -name .git | xargs -n 1 dirname | sort)
do
	echo $name
	echo ============================================================================
  cd $name

  [[ -n `git config repo.remote` ]] \
    && rem=`git config repo.remote` || rem='upstream'
  [[ -n `git config repo.branch` ]] \
    && brm=`git config repo.branch` || brm='master'

  cur=`git symbolic-ref HEAD 2>/dev/null | cut -d"/" -f 3`
  if [[ $cur != $brm ]]
  then
    git checkout $brm
  fi
  git pull $rem $brm
  if [[ $cur != $brm ]]
  then
    git checkout $cur
  fi
	echo
done
