#!/bin/bash
[[ -n `git config --global repo.dir` ]] \
  && dir=`git config --global repo.dir` || dir=~/
[[ -n `git config --local repo.main` ]] \
  && rem=`git config --local repo.main` || rem='upstream'
[[ -n `git config --local repo.branch` ]] \
  && brm=`git config --local repo.branch` || brm='master'

IFS=$'\n'
for name in $(find $dir -type d -name .git | xargs -n 1 dirname | sort)
do
  cd $name
  cur=`git symbolic-ref HEAD 2>/dev/null | cut -d"/" -f 3`
  if [[ $cur != $brm ]]
  then
    git checkout $brm
  fi
  git pull $rem $brm
  if [[ $cur != $brm ]]
  then
    git checkout $cur
  fi
done
